---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: file:///home/m1036894/Downloads/centos65-1.0.7.box
      #box_url: learningchef/centos65

suites:
  - name: default
    run_list:
    attributes:
